WPM_ENABLE = yes
OLED_DRIVER_ENABLE = yes
OLED_ENABLE = yes
NKRO_ENABLE = yes
SPLIT_KEYBOARD = yes
SPLIT_LAYER_STATE_ENABLE = yes
TAP_DANCE_ENABLE = yes
ENCODER_ENABLE = yes
VIA_ENABLE = no

# No's

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
